### ISSUE TITLE
Class field initialization false positives?

### ISSUE THREAD

**Issue by ziacik** [lukastaegert/eslint-plugin-tree-shaking#101]
Hi, is this a bug?

This
![image](https://github.com/lukastaegert/eslint-plugin-tree-shaking/assets/4528506/42d1bde9-b8ec-47b9-8454-4c2ba3f63d70)

and this
![image](https://github.com/lukastaegert/eslint-plugin-tree-shaking/assets/4528506/784a37d3-b1a5-42c7-a750-5bc9df06dc2d)

is syntactically equivalent, isn't it?

It should not give error in the first case, should it?

**Comment by lukastaegert** [comment]
Yes, but the plugin is quite old and badly maintained, which is why advanced logic for class fields is missing.

**Comment by ziacik** [comment]
@lukastaegert 

Thanks for your reply.

I'd be happy to try providing a PR, but I noticed this particular case is explicitly set as invalid in tests.
I'm unable to identify a reason for this decision. Could you please offer an explanation why this is considered a possible side effect?

https://github.com/lukastaegert/eslint-plugin-tree-shaking/blob/c4244001b21d05bf3e689660247be00dff20d495/tests/lib/rules/no-side-effects-in-initialization.js#L771-L780

**Comment by ziacik** [comment]
Yes, `ext` can have side effects, but it is only called at class construction, so it shouldn't be considered side-effected unless the class is globally constructed, no?

**Comment by ziacik** [comment]
I've created a PR for this. If you agree with my points, I'd appreciate if you could review and merge the PR. Thank you.
