### ISSUE TITLE
Unknown node type JSXElement.

### ISSUE THREAD

**Issue by kurtextrem** [lukastaegert/eslint-plugin-tree-shaking#3]
Code:
```jsx
const loading = <Loading />
```

**Comment by lukastaegert** [comment]
The Plugin should now support all JSX-Elements that I could replicate in tests. These are basically all nodes given in https://github.com/facebook/jsx/blob/master/AST.md (+ some reasonable side-effect detection) except JSXSpreadElement and JSXText.

**Comment by kurtextrem** [comment]
Works great, thank you!
